# 1. ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow-runner
  namespace: sys-argo-workflows
---
# 2. Role - internals
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-runner-executor
  namespace: sys-argo-workflows
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtaskresults"]
    verbs: ["create", "patch"]
  - apiGroups: [""]
    # for cross-cluster workaround
    resources: ["secrets"]
    resourceNames: ["cluster-tokens"]
    verbs: ["get"]
---
# 3. RoleBinding - internals
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-runner-executor
  namespace: sys-argo-workflows
subjects:
  - kind: ServiceAccount
    name: workflow-runner
    namespace: sys-argo-workflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflow-runner-executor
---
# 4. ClusterRole - cross-namespace job orchestration
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workflow-job-orchestrator
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get"]
---
# 5. ClusterRoleBinding - cross-namespace job orchestration
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workflow-runner-job-orchestrator
subjects:
  - kind: ServiceAccount
    name: workflow-runner
    namespace: sys-argo-workflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workflow-job-orchestrator
