apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: CronWorkflow
      name: data-export-bills-total-api
    path: data-export-bills-total-api.yaml
