kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: qe-argo-workflows-admin
subjects:
  - kind: User
    name: fdaniels@uw.co.uk
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
