apiVersion: v1
kind: LimitRange
metadata:
  name: default
spec:
  limits:
    - default:
        cpu: 1000m
        ephemeral-storage: 1Gi
        memory: 64Mi
      defaultRequest:
        cpu: 0m
        ephemeral-storage: 0
        memory: 0Mi
      max:
        cpu: 6000m
      type: Container
