apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow-step-executor
  annotations:
    vault.uw.systems/aws-role: "arn:aws:iam::950135041896:role/dev-enablement-argo-workflows-bucket-rw"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-step-executor
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtaskresults"]
    verbs: ["create", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
      - job-executor-tokens
      - cluster-ca-certs
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-step-executor
subjects:
  - kind: ServiceAccount
    name: workflow-step-executor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflow-step-executor
