apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: CronWorkflow
      name: data-export-energy-tariff-system
    path: data-export-energy-tariff-system.yaml
