apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: ServiceAccount
      name: data-orchestrator
    patch: |
      - op: replace
        path: /metadata/annotations/vault.uw.systems~1aws-role
        value: "arn:aws:iam::950135041896:role/staging-ept-data-orchestrator-rw"

secretGenerator:
  - name: data-orchestrator-db
    envs:
      - secrets/data-orchestrator-db.env

generatorOptions:
  disableNameSuffixHash: true
