apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: CronWorkflow
      name: data-export-account-api
    path: data-export-account-api.yaml
  - target:
      kind: CronWorkflow
      name: data-export-legacy-account
    path: data-export-legacy-account.yaml
