# https://argo-workflows.readthedocs.io/en/latest/workflow-controller-configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  artifactRepository: |
    archiveLogs: true
    s3:
      bucket: argo-artifacts
      endpoint: minio.minio.svc.cluster.local:9000
      insecure: true
      accessKeySecret:
        name: minio-creds
        key: accesskey
      secretKeySecret:
        name: minio-creds
        key: secretkey
  namespaceParallelism: "1"
  parallelism: "1"
  resourceRateLimit: |
    limit: 10
    burst: 25
