apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterworkflowtemplates.argoproj.io.yaml
  - cronworkflows.argoproj.io.yaml
  - workflowartifactgctasks.argoproj.io.yaml
  - workfloweventbindings.argoproj.io.yaml
  - workflows.argoproj.io.yaml
  - workflowtaskresults.argoproj.io.yaml
  - workflowtasksets.argoproj.io.yaml
  - workflowtemplates.argoproj.io.yaml
