apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - upstream/configmap.yaml
  - upstream/deployment.yaml
  # - upstream/priorityclass.yaml
  - upstream/role.yaml
  - upstream/rolebinding.yaml
  - upstream/serviceaccount.yaml

patches:
  - path: patches/role.yaml
    target:
      kind: Role
      name: argo-role
  - path: patches/argo-server.yaml
    target:
      kind: ConfigMap
      name: workflow-controller-configmap
  - path: patches/argo-server-sa.yaml
    target:
      kind: ServiceAccount
      name: argo-server
