apiVersion: v1
kind: LimitRange
metadata:
  name: default
spec:
  limits:
    - default:
        cpu: 2
        ephemeral-storage: 1Gi
        memory: 1Gi
      defaultRequest:
        cpu: 0m
        ephemeral-storage: 0
        memory: 0Mi
      max:
        cpu: 4
      type: Container
